baseURL = "https://joeyjoey1234.github.io/elpmesh-prop2/"
title   = "El Paso Mesh"
languageCode = "en-us"
publishDir = "../docs"
enableGitInfo = true

[module]
  [[module.imports]]
    path = "github.com/google/docsy"
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"

[outputs]
  section = ["HTML", "JSON"]

[params]
  description = "Meshtastic El Paso — Docs, News, Map & Links"
  [params.ui]
    showLightDarkModeMenu = true
    sidebar_menu_compact  = true
    navbar_logo = "/logo.svg"   # explicit navbar logo path (fallback to static)

[menu]
  [[menu.main]]
    name = "Docs"
    url  = "/docs/"
    weight = 10
  [[menu.main]]
    name = "News"
    url  = "/news/"
    weight = 20
  [[menu.main]]
    name = "Map"
    url  = "/map/"
    weight = 30
  [[menu.main]]
    name = "Links"
    url  = "/links/"
    weight = 40
  [[menu.main]]
    name = "Discord"
    url  = "https://discord.gg/elp-mesh"
    weight = 50
